references:
  tags: &tags
    Name: go-serverless
    Provisioner: ServerlessFramework    

service: go-serverless

provider:
  name: aws
  runtime: go1.x
  region: us-east-1
  memorySize: 128
  versionFunctions: false

package:
  individually: true


functions:
  hello-world:
    name: hello-world-${self:custom.stage}
    handler: bin/hello-world
    package: 
      artifact: bin/hello-world.zip
    timeout: 30
    events:
      - httpApi:
          method: GET
          path: /hello
          cors: true 

custom:
  stage: ${opt:stage, self:provider.stage}

