package main

import (
	"context"
	"testing"

	"github.com/aws/aws-lambda-go/events"
)

// This test was generated by co-pilot
func TestHandler(t *testing.T) {
	// Create a new handler with a greeting
	h := newHandler("Hello World!")

	// Create a new context
	ctx := context.Background()

	// Create a new request
	r := events.APIGatewayProxyRequest{
		Body: "Hello World!",
	}

	// Invoke the handler
	resp, err := h.handleRequest(ctx, r)

	// Check the response
	if err != nil {
		t.Fatal(err)
	}

	// Check the response
	if resp.Body != "Hello World!" {
		t.Fatalf("expected %s, got %s", "Hello World!", resp.Body)
	}
}
